name: Deploy Pods and Services to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1 # Replace with your AWS region
  CLUSTER_NAME: harisheks  # Replace with your EKS cluster name
  NAMESPACE: my-namespace  # Replace with your namespac

jobs:
  deploy:
    name: Deploy Pod and Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig with EKS credentials
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} --kubeconfig ~/.kube/config

      - name: Verify kubeconfig
        run: kubectl config view

      - name: Apply deployment.yml
        run: kubectl apply -f deployment.yml -n ${{ env.NAMESPACE }}

      - name: Apply service.yml
        run: kubectl apply -f service.yml -n ${{ env.NAMESPACE }}
